/**
 * Auto-generated by scripts/build-gallery.mjs — do not edit by hand.
 */
const galleryItems = [
  {
    id: 1,
    image: "../images/gallery/event-gallery-001.jpg",
    title: "Staff Meeting",
    category: "Exhibitions",
    description: "Professional exhibitions conducted by Parama.",
    date: "2026",
    featured: true,
    alt: "Staff Meeting — Exhibitions at Parama"
  },
  {
    id: 2,
    image: "../images/gallery/event-gallery-002.jpg",
    title: "Annual Celebration",
    category: "Business Meetings",
    description: "Professional business meetings conducted by Parama.",
    date: "2026",
    featured: true,
    alt: "Annual Celebration — Business Meetings at Parama"
  },
  {
    id: 3,
    image: "../images/gallery/event-gallery-003.jpg",
    title: "Team Building Session",
    category: "Factory Operations",
    description: "Professional factory operations conducted by Parama.",
    date: "2026",
    featured: true,
    alt: "Team Building Session — Factory Operations at Parama"
  },
  {
    id: 4,
    image: "../images/gallery/event-gallery-004.jpg",
    title: "Management Meeting",
    category: "Factory Operations",
    description: "Professional factory operations conducted by Parama.",
    date: "2026",
    featured: true,
    alt: "Management Meeting — Factory Operations at Parama"
  },
  {
    id: 5,
    image: "../images/gallery/event-gallery-005.jpg",
    title: "Management Meeting",
    category: "CSR Programs",
    description: "Professional csr programs conducted by Parama.",
    date: "2026",
    featured: true,
    alt: "Management Meeting — CSR Programs at Parama"
  },
  {
    id: 6,
    image: "../images/gallery/event-gallery-006.jpg",
    title: "Annual Celebration",
    category: "Exhibitions",
    description: "Professional exhibitions conducted by Parama.",
    date: "2026",
    featured: true,
    alt: "Annual Celebration — Exhibitions at Parama"
  },
  {
    id: 7,
    image: "../images/gallery/event-gallery-007.jpg",
    title: "Team Building Session",
    category: "Special Events",
    description: "Professional special events conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Team Building Session — Special Events at Parama"
  },
  {
    id: 8,
    image: "../images/gallery/event-gallery-008.jpg",
    title: "Staff Meeting",
    category: "Staff Activities",
    description: "Professional staff activities conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Staff Meeting — Staff Activities at Parama"
  },
  {
    id: 9,
    image: "../images/gallery/event-gallery-009.jpg",
    title: "Staff Meeting",
    category: "Exhibitions",
    description: "Professional exhibitions conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Staff Meeting — Exhibitions at Parama"
  },
  {
    id: 10,
    image: "../images/gallery/event-gallery-010.jpg",
    title: "Team Activity",
    category: "Exhibitions",
    description: "Professional exhibitions conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Team Activity — Exhibitions at Parama"
  },
  {
    id: 11,
    image: "../images/gallery/event-gallery-011.jpg",
    title: "Management Meeting",
    category: "Special Events",
    description: "Professional special events conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Management Meeting — Special Events at Parama"
  },
  {
    id: 12,
    image: "../images/gallery/event-gallery-012.jpg",
    title: "Team Building Session",
    category: "Special Events",
    description: "Professional special events conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Team Building Session — Special Events at Parama"
  },
  {
    id: 13,
    image: "../images/gallery/event-gallery-013.jpg",
    title: "Team Building Session",
    category: "Special Events",
    description: "Professional special events conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Team Building Session — Special Events at Parama"
  },
  {
    id: 14,
    image: "../images/gallery/event-gallery-014.jpg",
    title: "Management Meeting",
    category: "Exhibitions",
    description: "Professional exhibitions conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Management Meeting — Exhibitions at Parama"
  },
  {
    id: 15,
    image: "../images/gallery/event-gallery-015.jpg",
    title: "Staff Meeting",
    category: "CSR Programs",
    description: "Professional csr programs conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Staff Meeting — CSR Programs at Parama"
  },
  {
    id: 16,
    image: "../images/gallery/event-gallery-016.jpg",
    title: "Team Building Session",
    category: "Factory Operations",
    description: "Professional factory operations conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Team Building Session — Factory Operations at Parama"
  },
  {
    id: 17,
    image: "../images/gallery/event-gallery-017.jpg",
    title: "Team Building Session",
    category: "Factory Operations",
    description: "Professional factory operations conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Team Building Session — Factory Operations at Parama"
  },
  {
    id: 18,
    image: "../images/gallery/event-gallery-018.jpg",
    title: "Staff Meeting",
    category: "CSR Programs",
    description: "Professional csr programs conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Staff Meeting — CSR Programs at Parama"
  },
  {
    id: 19,
    image: "../images/gallery/event-gallery-019.jpg",
    title: "Management Meeting",
    category: "Special Events",
    description: "Professional special events conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Management Meeting — Special Events at Parama"
  },
  {
    id: 20,
    image: "../images/gallery/event-gallery-020.jpg",
    title: "CSR Activity",
    category: "Factory Operations",
    description: "Professional factory operations conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "CSR Activity — Factory Operations at Parama"
  },
  {
    id: 21,
    image: "../images/gallery/event-gallery-021.jpg",
    title: "Business Conference",
    category: "CSR Programs",
    description: "Professional csr programs conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Business Conference — CSR Programs at Parama"
  },
  {
    id: 22,
    image: "../images/gallery/event-gallery-022.jpg",
    title: "Business Conference",
    category: "Factory Operations",
    description: "Professional factory operations conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Business Conference — Factory Operations at Parama"
  },
  {
    id: 23,
    image: "../images/gallery/event-gallery-023.jpg",
    title: "Company Gathering",
    category: "CSR Programs",
    description: "Professional csr programs conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Company Gathering — CSR Programs at Parama"
  },
  {
    id: 24,
    image: "../images/gallery/event-gallery-024.jpg",
    title: "Exhibition Program",
    category: "Special Events",
    description: "Professional special events conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Exhibition Program — Special Events at Parama"
  },
  {
    id: 25,
    image: "../images/gallery/event-gallery-025.jpg",
    title: "Leadership Summit",
    category: "Company Events",
    description: "Professional company events conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Leadership Summit — Company Events at Parama"
  },
  {
    id: 26,
    image: "../images/gallery/event-gallery-026.jpg",
    title: "Leadership Summit",
    category: "Factory Operations",
    description: "Professional factory operations conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Leadership Summit — Factory Operations at Parama"
  },
  {
    id: 27,
    image: "../images/gallery/event-gallery-027.jpg",
    title: "Company Gathering",
    category: "Exhibitions",
    description: "Professional exhibitions conducted by Parama.",
    date: "2026",
    featured: false,
    alt: "Company Gathering — Exhibitions at Parama"
  }
];
