#!/usr/bin/env node
/**
 * Regenerate gallery/gallery-data.js from images/gallery/event-gallery-*.jpg
 *
 * Usage: node scripts/build-gallery.mjs
 *        npm run build:gallery
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const GALLERY_DIR = path.join(ROOT, 'images', 'gallery');
const OUT_FILE = path.join(ROOT, 'gallery', 'gallery-data.js');

const FEATURED_COUNT = 6;
const CATEGORY = 'Corporate Events';
const DESCRIPTION = 'Photo from Parama corporate events and company activities.';

function listGalleryImages() {
  if (!fs.existsSync(GALLERY_DIR)) {
    throw new Error(`Gallery directory not found: ${GALLERY_DIR}`);
  }

  return fs
    .readdirSync(GALLERY_DIR)
    .filter((name) => /^event-gallery-\d+\.jpe?g$/i.test(name))
    .sort((a, b) => {
      const na = parseInt(a.match(/\d+/)?.[0] ?? '0', 10);
      const nb = parseInt(b.match(/\d+/)?.[0] ?? '0', 10);
      return na - nb;
    });
}

function buildItem(id, filename) {
  const title = `Corporate event photo ${id}`;
  const alt = `${title} — Parama Group`;
  return {
    id,
    image: `../images/gallery/${filename}`,
    title,
    category: CATEGORY,
    description: DESCRIPTION,
    date: '2026',
    featured: id <= FEATURED_COUNT,
    alt,
  };
}

function formatItem(item) {
  const lines = [
    '  {',
    `    id: ${item.id},`,
    `    image: "${item.image}",`,
    `    title: "${item.title}",`,
    `    category: "${item.category}",`,
    `    description: "${item.description}",`,
    `    date: "${item.date}",`,
    `    featured: ${item.featured},`,
    `    alt: "${item.alt}"`,
    '  }',
  ];
  return lines.join('\n');
}

function main() {
  const files = listGalleryImages();
  if (!files.length) {
    console.warn('No event-gallery-*.jpg files found in images/gallery/');
    process.exit(1);
  }

  const items = files.map((file, i) => buildItem(i + 1, file));
  const body = items.map(formatItem).join(',\n');

  const output = `/**
 * Auto-generated by scripts/build-gallery.mjs — do not edit by hand.
 * Regenerate: npm run build:gallery
 */
const galleryItems = [
${body}
];
`;

  fs.writeFileSync(OUT_FILE, output, 'utf8');
  console.log(`Wrote ${items.length} items to ${path.relative(ROOT, OUT_FILE)}`);
}

main();
